default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
          - --keep-runtime-typing
  - repo: https://github.com/pycqa/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
          - flake8-print
          - flake8-pytest-style
          - flake8-datetimez
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
          - flake8-print
          - flake8-pytest-style
          - flake8-datetimez
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [markdown]
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
      - id: check-manifest
        args: ["--no-build-isolation"]

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
    | docs
    | LICENSE\.md
  )
