site_name: RESPX
site_description: A utility for mocking out the Python HTTPX library.
site_url: https://lundberg.github.io/respx/

theme:
  name: "material"
  icon:
    logo: "material/school"
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/slate.css

repo_name: lundberg/respx
repo_url: https://github.com/lundberg/respx
edit_uri: ""

nav:
  - Introduction: "index.md"
  - User Guide: "guide.md"
  - API Reference: "api.md"
  - Test Case Examples: "examples.md"
  - Migrate from requests: "migrate.md"
  - Upgrading: "upgrade.md"
  - Older Versions:
    - 0.14.0:
      - Mock HTTPX: "versions/0.14.0/mocking.md"
      - Developer Interface: "versions/0.14.0/api.md"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
