name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: |
          ${{ runner.os }}-pip
    - name: Build
      run: |
        pip install --upgrade nox
        nox -s docs
    - name: Publish
      if: github.repository == 'lundberg/respx'
      run: |
        git config user.email ${{ secrets.GITHUB_EMAIL }}
        git remote set-url origin https://${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_PAGES_TOKEN }}@github.com/lundberg/respx.git
        ./.nox/docs/bin/mkdocs gh-deploy --force
