name: publish-docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: pip install nox
    - name: Build
      run: nox -N -s docs
    - name: Publish
      if: github.repository_owner == 'lundberg'
      run: |
        git config user.email ${{ secrets.GITHUB_EMAIL }}
        git remote set-url origin https://${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_PAGES_TOKEN }}@github.com/lundberg/respx.git
        ./.nox/docs/bin/mkdocs gh-deploy --force
