name: test

on: [push, pull_request]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10-dev"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: |
          ${{ runner.os }}-pip
    - name: Test
      run: |
        pip install --upgrade nox
        # Strip any "-dev" suffix
        target=$(echo ${{ matrix.python-version }} | sed -e "s/-dev$//")
        nox -s test-${target}
    - name: Upload report
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        name: Python ${{ matrix.python-version }}

  lint:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: |
          ${{ runner.os }}-pip
    - name: Lint
      run: |
        pip install --upgrade nox
        nox -k "check + docs"
