name: test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install nox
    - name: Test
      run: nox -N -s test-${{ matrix.python-version }} -- -v
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        name: Python ${{ matrix.python-version }}
        files: ./coverage.xml
        fail_ci_if_error: true

  check-types:
    name: Check Typing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - run: pip install nox
      - name: Run mypy
        run: nox -N -s mypy
